route:
  receiver: "telegram"
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h

receivers:
  - name: "telegram"
    telegram_configs:
      - bot_token: "tokenbot"
        chat_id: chatid
