services:
  ############################################################
  # 1) MINIO
  ############################################################
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: "minio"
      MINIO_ROOT_PASSWORD: "qwe12345"
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
    volumes:
      - ./data:/data
    command: server --address ":9000" --console-address ":9090" /data
    networks:
      - minio_net

  ############################################################
  # 2) PROMETHEUS
  ############################################################
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml:ro
    depends_on:
      - minio
    networks:
      - minio_net

  ############################################################
  # 3) GRAFANA
  ############################################################
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
    networks:
      - minio_net

  ############################################################
  # 4) NGINX
  ############################################################
  nginx:
    image: nginx:stable-alpine
    container_name: minio-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /var/cache/nginx:/var/cache/nginx
    networks:
      - minio_net
    depends_on:
      - minio

  ############################################################
  # 5) ALERTMANAGER
  ############################################################
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    depends_on:
      - prometheus
    networks:
      - minio_net

networks:
  minio_net:
    driver: bridge
